image: registry.gitlab.com/cardboardwm/cardboard-ci-image/ci-image
stages:
  - build

gnu:
  stage: build
  script:
    - CC=gcc CXX=g++ meson build-gnu
    - ninja -C build-gnu

clang:
  stage: build
  script:
    - CC=clang CXX=clang++ meson build-clang
    - ninja -C build-clang
