#ifndef WLR_VERSION_H
#define WLR_VERSION_H

#define WLR_VERSION_STR "0.10.0"

#define WLR_VERSION_MAJOR 0
#define WLR_VERSION_MINOR 10
#define WLR_VERSION_MICRO 0

#define WLR_VERSION_NUM ((WLR_VERSION_MAJOR << 16) | (WLR_VERSION_MINOR << 8) | WLR_VERSION_MICRO)

#define WLR_VERSION_API_CURRENT 5
#define WLR_VERSION_API_REVISION 9
#define WLR_VERSION_API_AGE 1

#endif
